service: lighthouse-layer

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

layers:
  lighthouse:
    path: ./layer
    description: Layer with all the required dependencies to run google lighthouse
    compatibleRuntimes:
      - nodejs10.x
    licenseInfo: MIT
    retain: true
