service: lighthouse-layer

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

layers:
  lighthouse:
    path: ./layer
    description: Layer with all the required dependencies to run google lighthouse
    compatibleRuntimes:
      - nodejs8.10 # https://github.com/alixaxel/chrome-aws-lambda/issues/37
    licenseInfo: MIT
    retain: true
